package org.hawaiiframework.errors.token;

import org.hawaiiframework.exception.ApiException;

import static org.hawaiiframework.errors.ErrorCode.INVALID_TOKEN;

/**
 * ApiException with a {@link org.hawaiiframework.errors.ErrorCode#INVALID_TOKEN}.
 */
public class InvalidTokenException extends ApiException {

    /**
     * Generated by IntelliJ IDEA.
     */
    private static final long serialVersionUID = -2998388389767882298L;

    /**
     * The InvalidTokenException default constructor.
     */
    public InvalidTokenException() {
        this(null, null);
    }

    /**
     * The InvalidTokenException message constructor.
     */
    public InvalidTokenException(final String message) {
        this(null, message);
    }

    /**
     * The InvalidTokenException throwable constructor.
     */
    public InvalidTokenException(final Throwable orig) {
        this(orig, null);
    }

    /**
     * The InvalidTokenException constructor.
     */
    public InvalidTokenException(final Throwable orig, final String message) {
        super(INVALID_TOKEN, orig, message);
    }

}
