package org.hawaiiframework.errors.sso;


import org.hawaiiframework.errors.ErrorCode;
import org.hawaiiframework.exception.ApiException;

/**
 * Exception thrown when a user fills in a wrong password for the first time.
 */
public class SmsMaxTriesExceededException extends ApiException {

    /**
     * Generated by IntelliJ IDEA.
     */
    private static final long serialVersionUID = 5470192954132030137L;

    /**
     * Constructor.
     */
    public SmsMaxTriesExceededException() {
        super(ErrorCode.MAX_TRIES_EXCEEDED);
    }
}
