package org.hawaiiframework.errors.sso;

import org.hawaiiframework.errors.ErrorCode;
import org.hawaiiframework.exception.ApiException;

/**
 * Exception thrown when a user fills in a wrong password for the third time. The user is now locked.
 */
public class WrongPasswordLockedException extends ApiException {

    /**
     * Generated by IntelliJ IDEA.
     */
    private static final long serialVersionUID = 4142510722746335099L;

    /**
     * Constructor.
     */
    public WrongPasswordLockedException() {
        super(ErrorCode.WRONG_PASSWORD_NOW_LOCKED);
    }
}
