package org.hawaiiframework.errors.query;

import org.hawaiiframework.errors.ErrorCode;
import org.hawaiiframework.exception.ApiException;

/**
 * Thrown when searching without any search criteria.
 *
 * This is an ApiException with error code {@link ErrorCode#NO_SEARCH_CRITERIA_PROVIDED}.
 */
public class NoSearchCriteriaProvidedException extends ApiException {

    /**
     * Generated by IntelliJ IDEA.
     */
    private static final long serialVersionUID = -8986438498805612704L;

    /**
     * Construct an instance.
     */
    public NoSearchCriteriaProvidedException() {
        super(ErrorCode.NO_SEARCH_CRITERIA_PROVIDED);
    }
}
