[[introduction]]
== Introduction to Hawaii

The Hawaii Framework is a Java framework for developing Spring based applications.

It provides production-ready features and integrations based best practices and experience to boost projects.

The Hawaii Framework is developed internally at https://qnh.eu[QNH] and is used in projects for medium and large
enterprise customers.

[[introduction-spring-boot]]
=== Spring Boot

Combining http://projects.spring.io/spring-boot[Spring Boot] and the Hawaii production-ready features and auto
configuration brings even more power and simplicity to developers, without sacrificing flexibility.

The Hawaii Framework also provides various Spring Boot Starters to automatically include the needed dependencies and
trigger the auto configuration of the Hawaii production-ready features.

But it is important to mention that most of the Hawaii features can also used without using Spring Boot.
In that case the desired features need to be configured manually by defining the appropriate Spring beans inside the
application's context.
